services: 
  nginx: 
    build: 
      context: ./app
      args:
        VITE_API_HOST: /v1
    restart: always
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
     - 8000:80
    depends_on:
       - server

  db:
    image: postgres:latest
    container_name: boutique_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "3503"
      POSTGRES_DB: Boutique
    ports:
     - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  server: 
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
       - DATABASE_URL=postgres://postgres:3503@boutique_db:5432/Boutique?schema=public
    ports: 
      - "3000:3000"
    depends_on:
      - db
    command: ["/bin/sh", "-c", "./start.sh"]
